name 'fnmoc_ci'
maintainer 'Dan Jones'
maintainer_email 'daniel.jones4@navy.mil'
license 'all_rights'
description 'Installs/Configures fnmoc_ci'
long_description 'Installs/Configures fnmoc_ci'
version '0.1.0'
depends 'httpd', '~> 0.4'
depends 'java'
